### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by sushidelivery** [ycao5602/SAL#1]
Hey ! How are you? Thank you so much for sharing your work! 

I would like to ask you, when the pre-trained models will be released? 

Thanks!

**Comment by ycao5602** [comment]
Thank you for your interest! I'll get the link for pre-trained and state-of-the-art models prepared within the month.

**Comment by sushidelivery** [comment]
cool! thank you so much!

And also could you please, release the demo.py, so we could visualize results as you did in the picture. That would be great, if you could do that.  

Thanks!

**Comment by ycao5602** [comment]
Do you mean visualizing the ranked results? You can try adding '--evaluate --visualize-ranks' in the script together with loading trained models, then the visualized results for the models loaded will be saved in your target folder.
